// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmoswcvglykvistxtwoc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhtb3N3Y3ZnbHlrdmlzdHh0d29jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxODMyNTEsImV4cCI6MjA1ODc1OTI1MX0.MeNd7cDNTRIR2RFouAfPkKAEOKE2PsA2JLY7u_Vjruk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);